[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read-write", path = "./"}]

[profile]
openzeppelin-contracts = "lib/openzeppelin-contracts/contracts/"

[rpc_endpoints]
default_network = "https://virtual.mainnet.rpc.tenderly.co/32761de4-da0a-455a-8a72-1b42b510e5e9"


tenderly = "https://virtual.mainnet.rpc.tenderly.co/32761de4-da0a-455a-8a72-1b42b510e5e9"


localhost = "http://127.0.0.1:8545"

[etherscan]
polygonMumbai = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }



[fmt]
line_length = 120
tab_width = 4
quote_style = "double"
bracket_spacing = true
int_types = "long"




# See more config options https://book.getfoundry.sh/reference/config/overview